package com.it.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class HonorExample {
    /**
     * This field corresponds to the database table honor
     */
    protected String orderByClause;

    /**
     * This field corresponds to the database table honor
     */
    protected boolean distinct;

    /**
     * This field corresponds to the database table honor
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method corresponds to the database table honor
     */
    public HonorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method corresponds to the database table honor
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method corresponds to the database table honor
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method corresponds to the database table honor
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method corresponds to the database table honor
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method corresponds to the database table honor
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method corresponds to the database table honor
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method corresponds to the database table honor
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method corresponds to the database table honor
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method corresponds to the database table honor
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method corresponds to the database table honor
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table honor
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andHonorIdIsNull() {
            addCriterion("honor_id is null");
            return (Criteria) this;
        }

        public Criteria andHonorIdIsNotNull() {
            addCriterion("honor_id is not null");
            return (Criteria) this;
        }

        public Criteria andHonorIdEqualTo(Integer value) {
            addCriterion("honor_id =", value, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdNotEqualTo(Integer value) {
            addCriterion("honor_id <>", value, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdGreaterThan(Integer value) {
            addCriterion("honor_id >", value, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("honor_id >=", value, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdLessThan(Integer value) {
            addCriterion("honor_id <", value, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdLessThanOrEqualTo(Integer value) {
            addCriterion("honor_id <=", value, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdIn(List<Integer> values) {
            addCriterion("honor_id in", values, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdNotIn(List<Integer> values) {
            addCriterion("honor_id not in", values, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdBetween(Integer value1, Integer value2) {
            addCriterion("honor_id between", value1, value2, "honorId");
            return (Criteria) this;
        }

        public Criteria andHonorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("honor_id not between", value1, value2, "honorId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNull() {
            addCriterion("resume_id is null");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNotNull() {
            addCriterion("resume_id is not null");
            return (Criteria) this;
        }

        public Criteria andResumeIdEqualTo(Integer value) {
            addCriterion("resume_id =", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotEqualTo(Integer value) {
            addCriterion("resume_id <>", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThan(Integer value) {
            addCriterion("resume_id >", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("resume_id >=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThan(Integer value) {
            addCriterion("resume_id <", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThanOrEqualTo(Integer value) {
            addCriterion("resume_id <=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIn(List<Integer> values) {
            addCriterion("resume_id in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotIn(List<Integer> values) {
            addCriterion("resume_id not in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdBetween(Integer value1, Integer value2) {
            addCriterion("resume_id between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("resume_id not between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeIsNull() {
            addCriterion("honor_create_time is null");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeIsNotNull() {
            addCriterion("honor_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeEqualTo(Date value) {
            addCriterionForJDBCDate("honor_create_time =", value, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("honor_create_time <>", value, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("honor_create_time >", value, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("honor_create_time >=", value, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeLessThan(Date value) {
            addCriterionForJDBCDate("honor_create_time <", value, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("honor_create_time <=", value, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeIn(List<Date> values) {
            addCriterionForJDBCDate("honor_create_time in", values, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("honor_create_time not in", values, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("honor_create_time between", value1, value2, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorCreateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("honor_create_time not between", value1, value2, "honorCreateTime");
            return (Criteria) this;
        }

        public Criteria andHonorNameIsNull() {
            addCriterion("honor_name is null");
            return (Criteria) this;
        }

        public Criteria andHonorNameIsNotNull() {
            addCriterion("honor_name is not null");
            return (Criteria) this;
        }

        public Criteria andHonorNameEqualTo(String value) {
            addCriterion("honor_name =", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameNotEqualTo(String value) {
            addCriterion("honor_name <>", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameGreaterThan(String value) {
            addCriterion("honor_name >", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameGreaterThanOrEqualTo(String value) {
            addCriterion("honor_name >=", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameLessThan(String value) {
            addCriterion("honor_name <", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameLessThanOrEqualTo(String value) {
            addCriterion("honor_name <=", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameLike(String value) {
            addCriterion("honor_name like", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameNotLike(String value) {
            addCriterion("honor_name not like", value, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameIn(List<String> values) {
            addCriterion("honor_name in", values, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameNotIn(List<String> values) {
            addCriterion("honor_name not in", values, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameBetween(String value1, String value2) {
            addCriterion("honor_name between", value1, value2, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorNameNotBetween(String value1, String value2) {
            addCriterion("honor_name not between", value1, value2, "honorName");
            return (Criteria) this;
        }

        public Criteria andHonorGradeIsNull() {
            addCriterion("honor_grade is null");
            return (Criteria) this;
        }

        public Criteria andHonorGradeIsNotNull() {
            addCriterion("honor_grade is not null");
            return (Criteria) this;
        }

        public Criteria andHonorGradeEqualTo(String value) {
            addCriterion("honor_grade =", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeNotEqualTo(String value) {
            addCriterion("honor_grade <>", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeGreaterThan(String value) {
            addCriterion("honor_grade >", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeGreaterThanOrEqualTo(String value) {
            addCriterion("honor_grade >=", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeLessThan(String value) {
            addCriterion("honor_grade <", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeLessThanOrEqualTo(String value) {
            addCriterion("honor_grade <=", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeLike(String value) {
            addCriterion("honor_grade like", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeNotLike(String value) {
            addCriterion("honor_grade not like", value, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeIn(List<String> values) {
            addCriterion("honor_grade in", values, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeNotIn(List<String> values) {
            addCriterion("honor_grade not in", values, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeBetween(String value1, String value2) {
            addCriterion("honor_grade between", value1, value2, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andHonorGradeNotBetween(String value1, String value2) {
            addCriterion("honor_grade not between", value1, value2, "honorGrade");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table honor
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 26 09:56:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table honor
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}