package com.it.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JobExample {
    /**
     * This field corresponds to the database table job
     */
    protected String orderByClause;

    /**
     * This field corresponds to the database table job
     */
    protected boolean distinct;

    /**
     * This field corresponds to the database table job
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method corresponds to the database table job
     */
    public JobExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method corresponds to the database table job
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method corresponds to the database table job
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method corresponds to the database table job
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method corresponds to the database table job
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method corresponds to the database table job
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method corresponds to the database table job
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method corresponds to the database table job
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method corresponds to the database table job
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method corresponds to the database table job
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method corresponds to the database table job
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobIdIsNull() {
            addCriterion("job_id is null");
            return (Criteria) this;
        }

        public Criteria andJobIdIsNotNull() {
            addCriterion("job_id is not null");
            return (Criteria) this;
        }

        public Criteria andJobIdEqualTo(Integer value) {
            addCriterion("job_id =", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotEqualTo(Integer value) {
            addCriterion("job_id <>", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThan(Integer value) {
            addCriterion("job_id >", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_id >=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThan(Integer value) {
            addCriterion("job_id <", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdLessThanOrEqualTo(Integer value) {
            addCriterion("job_id <=", value, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdIn(List<Integer> values) {
            addCriterion("job_id in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotIn(List<Integer> values) {
            addCriterion("job_id not in", values, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdBetween(Integer value1, Integer value2) {
            addCriterion("job_id between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andJobIdNotBetween(Integer value1, Integer value2) {
            addCriterion("job_id not between", value1, value2, "jobId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("job_name is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("job_name is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("job_name =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("job_name <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("job_name >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("job_name >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("job_name <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("job_name <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("job_name like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("job_name not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("job_name in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("job_name not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("job_name between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("job_name not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobCityIsNull() {
            addCriterion("job_city is null");
            return (Criteria) this;
        }

        public Criteria andJobCityIsNotNull() {
            addCriterion("job_city is not null");
            return (Criteria) this;
        }

        public Criteria andJobCityEqualTo(String value) {
            addCriterion("job_city =", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityNotEqualTo(String value) {
            addCriterion("job_city <>", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityGreaterThan(String value) {
            addCriterion("job_city >", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityGreaterThanOrEqualTo(String value) {
            addCriterion("job_city >=", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityLessThan(String value) {
            addCriterion("job_city <", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityLessThanOrEqualTo(String value) {
            addCriterion("job_city <=", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityLike(String value) {
            addCriterion("job_city like", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityNotLike(String value) {
            addCriterion("job_city not like", value, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityIn(List<String> values) {
            addCriterion("job_city in", values, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityNotIn(List<String> values) {
            addCriterion("job_city not in", values, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityBetween(String value1, String value2) {
            addCriterion("job_city between", value1, value2, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobCityNotBetween(String value1, String value2) {
            addCriterion("job_city not between", value1, value2, "jobCity");
            return (Criteria) this;
        }

        public Criteria andJobYearIsNull() {
            addCriterion("job_year is null");
            return (Criteria) this;
        }

        public Criteria andJobYearIsNotNull() {
            addCriterion("job_year is not null");
            return (Criteria) this;
        }

        public Criteria andJobYearEqualTo(String value) {
            addCriterion("job_year =", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearNotEqualTo(String value) {
            addCriterion("job_year <>", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearGreaterThan(String value) {
            addCriterion("job_year >", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearGreaterThanOrEqualTo(String value) {
            addCriterion("job_year >=", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearLessThan(String value) {
            addCriterion("job_year <", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearLessThanOrEqualTo(String value) {
            addCriterion("job_year <=", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearLike(String value) {
            addCriterion("job_year like", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearNotLike(String value) {
            addCriterion("job_year not like", value, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearIn(List<String> values) {
            addCriterion("job_year in", values, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearNotIn(List<String> values) {
            addCriterion("job_year not in", values, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearBetween(String value1, String value2) {
            addCriterion("job_year between", value1, value2, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobYearNotBetween(String value1, String value2) {
            addCriterion("job_year not between", value1, value2, "jobYear");
            return (Criteria) this;
        }

        public Criteria andJobDegreeIsNull() {
            addCriterion("job_degree is null");
            return (Criteria) this;
        }

        public Criteria andJobDegreeIsNotNull() {
            addCriterion("job_degree is not null");
            return (Criteria) this;
        }

        public Criteria andJobDegreeEqualTo(String value) {
            addCriterion("job_degree =", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeNotEqualTo(String value) {
            addCriterion("job_degree <>", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeGreaterThan(String value) {
            addCriterion("job_degree >", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeGreaterThanOrEqualTo(String value) {
            addCriterion("job_degree >=", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeLessThan(String value) {
            addCriterion("job_degree <", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeLessThanOrEqualTo(String value) {
            addCriterion("job_degree <=", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeLike(String value) {
            addCriterion("job_degree like", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeNotLike(String value) {
            addCriterion("job_degree not like", value, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeIn(List<String> values) {
            addCriterion("job_degree in", values, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeNotIn(List<String> values) {
            addCriterion("job_degree not in", values, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeBetween(String value1, String value2) {
            addCriterion("job_degree between", value1, value2, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobDegreeNotBetween(String value1, String value2) {
            addCriterion("job_degree not between", value1, value2, "jobDegree");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberIsNull() {
            addCriterion("job_need_number is null");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberIsNotNull() {
            addCriterion("job_need_number is not null");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberEqualTo(Integer value) {
            addCriterion("job_need_number =", value, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberNotEqualTo(Integer value) {
            addCriterion("job_need_number <>", value, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberGreaterThan(Integer value) {
            addCriterion("job_need_number >", value, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("job_need_number >=", value, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberLessThan(Integer value) {
            addCriterion("job_need_number <", value, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberLessThanOrEqualTo(Integer value) {
            addCriterion("job_need_number <=", value, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberIn(List<Integer> values) {
            addCriterion("job_need_number in", values, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberNotIn(List<Integer> values) {
            addCriterion("job_need_number not in", values, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberBetween(Integer value1, Integer value2) {
            addCriterion("job_need_number between", value1, value2, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobNeedNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("job_need_number not between", value1, value2, "jobNeedNumber");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeIsNull() {
            addCriterion("job_publish_time is null");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeIsNotNull() {
            addCriterion("job_publish_time is not null");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeEqualTo(Date value) {
            addCriterion("job_publish_time =", value, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeNotEqualTo(Date value) {
            addCriterion("job_publish_time <>", value, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeGreaterThan(Date value) {
            addCriterion("job_publish_time >", value, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("job_publish_time >=", value, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeLessThan(Date value) {
            addCriterion("job_publish_time <", value, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeLessThanOrEqualTo(Date value) {
            addCriterion("job_publish_time <=", value, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeIn(List<Date> values) {
            addCriterion("job_publish_time in", values, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeNotIn(List<Date> values) {
            addCriterion("job_publish_time not in", values, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeBetween(Date value1, Date value2) {
            addCriterion("job_publish_time between", value1, value2, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobPublishTimeNotBetween(Date value1, Date value2) {
            addCriterion("job_publish_time not between", value1, value2, "jobPublishTime");
            return (Criteria) this;
        }

        public Criteria andJobWelfareIsNull() {
            addCriterion("job_welfare is null");
            return (Criteria) this;
        }

        public Criteria andJobWelfareIsNotNull() {
            addCriterion("job_welfare is not null");
            return (Criteria) this;
        }

        public Criteria andJobWelfareEqualTo(String value) {
            addCriterion("job_welfare =", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareNotEqualTo(String value) {
            addCriterion("job_welfare <>", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareGreaterThan(String value) {
            addCriterion("job_welfare >", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareGreaterThanOrEqualTo(String value) {
            addCriterion("job_welfare >=", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareLessThan(String value) {
            addCriterion("job_welfare <", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareLessThanOrEqualTo(String value) {
            addCriterion("job_welfare <=", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareLike(String value) {
            addCriterion("job_welfare like", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareNotLike(String value) {
            addCriterion("job_welfare not like", value, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareIn(List<String> values) {
            addCriterion("job_welfare in", values, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareNotIn(List<String> values) {
            addCriterion("job_welfare not in", values, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareBetween(String value1, String value2) {
            addCriterion("job_welfare between", value1, value2, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobWelfareNotBetween(String value1, String value2) {
            addCriterion("job_welfare not between", value1, value2, "jobWelfare");
            return (Criteria) this;
        }

        public Criteria andJobDutyIsNull() {
            addCriterion("job_duty is null");
            return (Criteria) this;
        }

        public Criteria andJobDutyIsNotNull() {
            addCriterion("job_duty is not null");
            return (Criteria) this;
        }

        public Criteria andJobDutyEqualTo(String value) {
            addCriterion("job_duty =", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyNotEqualTo(String value) {
            addCriterion("job_duty <>", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyGreaterThan(String value) {
            addCriterion("job_duty >", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyGreaterThanOrEqualTo(String value) {
            addCriterion("job_duty >=", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyLessThan(String value) {
            addCriterion("job_duty <", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyLessThanOrEqualTo(String value) {
            addCriterion("job_duty <=", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyLike(String value) {
            addCriterion("job_duty like", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyNotLike(String value) {
            addCriterion("job_duty not like", value, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyIn(List<String> values) {
            addCriterion("job_duty in", values, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyNotIn(List<String> values) {
            addCriterion("job_duty not in", values, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyBetween(String value1, String value2) {
            addCriterion("job_duty between", value1, value2, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDutyNotBetween(String value1, String value2) {
            addCriterion("job_duty not between", value1, value2, "jobDuty");
            return (Criteria) this;
        }

        public Criteria andJobDemandIsNull() {
            addCriterion("job_demand is null");
            return (Criteria) this;
        }

        public Criteria andJobDemandIsNotNull() {
            addCriterion("job_demand is not null");
            return (Criteria) this;
        }

        public Criteria andJobDemandEqualTo(String value) {
            addCriterion("job_demand =", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandNotEqualTo(String value) {
            addCriterion("job_demand <>", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandGreaterThan(String value) {
            addCriterion("job_demand >", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandGreaterThanOrEqualTo(String value) {
            addCriterion("job_demand >=", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandLessThan(String value) {
            addCriterion("job_demand <", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandLessThanOrEqualTo(String value) {
            addCriterion("job_demand <=", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandLike(String value) {
            addCriterion("job_demand like", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandNotLike(String value) {
            addCriterion("job_demand not like", value, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandIn(List<String> values) {
            addCriterion("job_demand in", values, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandNotIn(List<String> values) {
            addCriterion("job_demand not in", values, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandBetween(String value1, String value2) {
            addCriterion("job_demand between", value1, value2, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobDemandNotBetween(String value1, String value2) {
            addCriterion("job_demand not between", value1, value2, "jobDemand");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailIsNull() {
            addCriterion("job_addr_detail is null");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailIsNotNull() {
            addCriterion("job_addr_detail is not null");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailEqualTo(String value) {
            addCriterion("job_addr_detail =", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailNotEqualTo(String value) {
            addCriterion("job_addr_detail <>", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailGreaterThan(String value) {
            addCriterion("job_addr_detail >", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailGreaterThanOrEqualTo(String value) {
            addCriterion("job_addr_detail >=", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailLessThan(String value) {
            addCriterion("job_addr_detail <", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailLessThanOrEqualTo(String value) {
            addCriterion("job_addr_detail <=", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailLike(String value) {
            addCriterion("job_addr_detail like", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailNotLike(String value) {
            addCriterion("job_addr_detail not like", value, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailIn(List<String> values) {
            addCriterion("job_addr_detail in", values, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailNotIn(List<String> values) {
            addCriterion("job_addr_detail not in", values, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailBetween(String value1, String value2) {
            addCriterion("job_addr_detail between", value1, value2, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobAddrDetailNotBetween(String value1, String value2) {
            addCriterion("job_addr_detail not between", value1, value2, "jobAddrDetail");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryIsNull() {
            addCriterion("job_min_salary is null");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryIsNotNull() {
            addCriterion("job_min_salary is not null");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryEqualTo(BigDecimal value) {
            addCriterion("job_min_salary =", value, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryNotEqualTo(BigDecimal value) {
            addCriterion("job_min_salary <>", value, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryGreaterThan(BigDecimal value) {
            addCriterion("job_min_salary >", value, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("job_min_salary >=", value, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryLessThan(BigDecimal value) {
            addCriterion("job_min_salary <", value, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("job_min_salary <=", value, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryIn(List<BigDecimal> values) {
            addCriterion("job_min_salary in", values, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryNotIn(List<BigDecimal> values) {
            addCriterion("job_min_salary not in", values, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_min_salary between", value1, value2, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMinSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_min_salary not between", value1, value2, "jobMinSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryIsNull() {
            addCriterion("job_max_salary is null");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryIsNotNull() {
            addCriterion("job_max_salary is not null");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryEqualTo(BigDecimal value) {
            addCriterion("job_max_salary =", value, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryNotEqualTo(BigDecimal value) {
            addCriterion("job_max_salary <>", value, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryGreaterThan(BigDecimal value) {
            addCriterion("job_max_salary >", value, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("job_max_salary >=", value, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryLessThan(BigDecimal value) {
            addCriterion("job_max_salary <", value, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("job_max_salary <=", value, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryIn(List<BigDecimal> values) {
            addCriterion("job_max_salary in", values, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryNotIn(List<BigDecimal> values) {
            addCriterion("job_max_salary not in", values, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_max_salary between", value1, value2, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobMaxSalaryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("job_max_salary not between", value1, value2, "jobMaxSalary");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordIsNull() {
            addCriterion("job_search_keyword is null");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordIsNotNull() {
            addCriterion("job_search_keyword is not null");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordEqualTo(String value) {
            addCriterion("job_search_keyword =", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordNotEqualTo(String value) {
            addCriterion("job_search_keyword <>", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordGreaterThan(String value) {
            addCriterion("job_search_keyword >", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("job_search_keyword >=", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordLessThan(String value) {
            addCriterion("job_search_keyword <", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordLessThanOrEqualTo(String value) {
            addCriterion("job_search_keyword <=", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordLike(String value) {
            addCriterion("job_search_keyword like", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordNotLike(String value) {
            addCriterion("job_search_keyword not like", value, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordIn(List<String> values) {
            addCriterion("job_search_keyword in", values, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordNotIn(List<String> values) {
            addCriterion("job_search_keyword not in", values, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordBetween(String value1, String value2) {
            addCriterion("job_search_keyword between", value1, value2, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andJobSearchKeywordNotBetween(String value1, String value2) {
            addCriterion("job_search_keyword not between", value1, value2, "jobSearchKeyword");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 26 09:56:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table job
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}