package com.it.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ResumeExample {
    /**
     * This field corresponds to the database table resume
     */
    protected String orderByClause;

    /**
     * This field corresponds to the database table resume
     */
    protected boolean distinct;

    /**
     * This field corresponds to the database table resume
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method corresponds to the database table resume
     */
    public ResumeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method corresponds to the database table resume
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method corresponds to the database table resume
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method corresponds to the database table resume
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method corresponds to the database table resume
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method corresponds to the database table resume
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method corresponds to the database table resume
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method corresponds to the database table resume
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method corresponds to the database table resume
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method corresponds to the database table resume
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method corresponds to the database table resume
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resume
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andResumeIdIsNull() {
            addCriterion("resume_id is null");
            return (Criteria) this;
        }

        public Criteria andResumeIdIsNotNull() {
            addCriterion("resume_id is not null");
            return (Criteria) this;
        }

        public Criteria andResumeIdEqualTo(Integer value) {
            addCriterion("resume_id =", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotEqualTo(Integer value) {
            addCriterion("resume_id <>", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThan(Integer value) {
            addCriterion("resume_id >", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("resume_id >=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThan(Integer value) {
            addCriterion("resume_id <", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdLessThanOrEqualTo(Integer value) {
            addCriterion("resume_id <=", value, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdIn(List<Integer> values) {
            addCriterion("resume_id in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotIn(List<Integer> values) {
            addCriterion("resume_id not in", values, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdBetween(Integer value1, Integer value2) {
            addCriterion("resume_id between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andResumeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("resume_id not between", value1, value2, "resumeId");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNull() {
            addCriterion("cust_id is null");
            return (Criteria) this;
        }

        public Criteria andCustIdIsNotNull() {
            addCriterion("cust_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustIdEqualTo(Integer value) {
            addCriterion("cust_id =", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotEqualTo(Integer value) {
            addCriterion("cust_id <>", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThan(Integer value) {
            addCriterion("cust_id >", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_id >=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThan(Integer value) {
            addCriterion("cust_id <", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdLessThanOrEqualTo(Integer value) {
            addCriterion("cust_id <=", value, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdIn(List<Integer> values) {
            addCriterion("cust_id in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotIn(List<Integer> values) {
            addCriterion("cust_id not in", values, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdBetween(Integer value1, Integer value2) {
            addCriterion("cust_id between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andCustIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_id not between", value1, value2, "custId");
            return (Criteria) this;
        }

        public Criteria andResumeNameIsNull() {
            addCriterion("resume_name is null");
            return (Criteria) this;
        }

        public Criteria andResumeNameIsNotNull() {
            addCriterion("resume_name is not null");
            return (Criteria) this;
        }

        public Criteria andResumeNameEqualTo(String value) {
            addCriterion("resume_name =", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotEqualTo(String value) {
            addCriterion("resume_name <>", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameGreaterThan(String value) {
            addCriterion("resume_name >", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameGreaterThanOrEqualTo(String value) {
            addCriterion("resume_name >=", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameLessThan(String value) {
            addCriterion("resume_name <", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameLessThanOrEqualTo(String value) {
            addCriterion("resume_name <=", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameLike(String value) {
            addCriterion("resume_name like", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotLike(String value) {
            addCriterion("resume_name not like", value, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameIn(List<String> values) {
            addCriterion("resume_name in", values, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotIn(List<String> values) {
            addCriterion("resume_name not in", values, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameBetween(String value1, String value2) {
            addCriterion("resume_name between", value1, value2, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeNameNotBetween(String value1, String value2) {
            addCriterion("resume_name not between", value1, value2, "resumeName");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeIsNull() {
            addCriterion("resume_create_time is null");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeIsNotNull() {
            addCriterion("resume_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeEqualTo(Date value) {
            addCriterion("resume_create_time =", value, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeNotEqualTo(Date value) {
            addCriterion("resume_create_time <>", value, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeGreaterThan(Date value) {
            addCriterion("resume_create_time >", value, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resume_create_time >=", value, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeLessThan(Date value) {
            addCriterion("resume_create_time <", value, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("resume_create_time <=", value, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeIn(List<Date> values) {
            addCriterion("resume_create_time in", values, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeNotIn(List<Date> values) {
            addCriterion("resume_create_time not in", values, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeBetween(Date value1, Date value2) {
            addCriterion("resume_create_time between", value1, value2, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("resume_create_time not between", value1, value2, "resumeCreateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeIsNull() {
            addCriterion("resume_update_time is null");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeIsNotNull() {
            addCriterion("resume_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeEqualTo(Date value) {
            addCriterion("resume_update_time =", value, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeNotEqualTo(Date value) {
            addCriterion("resume_update_time <>", value, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeGreaterThan(Date value) {
            addCriterion("resume_update_time >", value, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("resume_update_time >=", value, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeLessThan(Date value) {
            addCriterion("resume_update_time <", value, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("resume_update_time <=", value, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeIn(List<Date> values) {
            addCriterion("resume_update_time in", values, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeNotIn(List<Date> values) {
            addCriterion("resume_update_time not in", values, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("resume_update_time between", value1, value2, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("resume_update_time not between", value1, value2, "resumeUpdateTime");
            return (Criteria) this;
        }

        public Criteria andResumeProfileIsNull() {
            addCriterion("resume_profile is null");
            return (Criteria) this;
        }

        public Criteria andResumeProfileIsNotNull() {
            addCriterion("resume_profile is not null");
            return (Criteria) this;
        }

        public Criteria andResumeProfileEqualTo(String value) {
            addCriterion("resume_profile =", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileNotEqualTo(String value) {
            addCriterion("resume_profile <>", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileGreaterThan(String value) {
            addCriterion("resume_profile >", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileGreaterThanOrEqualTo(String value) {
            addCriterion("resume_profile >=", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileLessThan(String value) {
            addCriterion("resume_profile <", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileLessThanOrEqualTo(String value) {
            addCriterion("resume_profile <=", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileLike(String value) {
            addCriterion("resume_profile like", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileNotLike(String value) {
            addCriterion("resume_profile not like", value, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileIn(List<String> values) {
            addCriterion("resume_profile in", values, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileNotIn(List<String> values) {
            addCriterion("resume_profile not in", values, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileBetween(String value1, String value2) {
            addCriterion("resume_profile between", value1, value2, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeProfileNotBetween(String value1, String value2) {
            addCriterion("resume_profile not between", value1, value2, "resumeProfile");
            return (Criteria) this;
        }

        public Criteria andResumeBirthIsNull() {
            addCriterion("resume_birth is null");
            return (Criteria) this;
        }

        public Criteria andResumeBirthIsNotNull() {
            addCriterion("resume_birth is not null");
            return (Criteria) this;
        }

        public Criteria andResumeBirthEqualTo(Date value) {
            addCriterionForJDBCDate("resume_birth =", value, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthNotEqualTo(Date value) {
            addCriterionForJDBCDate("resume_birth <>", value, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthGreaterThan(Date value) {
            addCriterionForJDBCDate("resume_birth >", value, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("resume_birth >=", value, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthLessThan(Date value) {
            addCriterionForJDBCDate("resume_birth <", value, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("resume_birth <=", value, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthIn(List<Date> values) {
            addCriterionForJDBCDate("resume_birth in", values, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthNotIn(List<Date> values) {
            addCriterionForJDBCDate("resume_birth not in", values, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("resume_birth between", value1, value2, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeBirthNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("resume_birth not between", value1, value2, "resumeBirth");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoIsNull() {
            addCriterion("resume_telno is null");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoIsNotNull() {
            addCriterion("resume_telno is not null");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoEqualTo(Long value) {
            addCriterion("resume_telno =", value, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoNotEqualTo(Long value) {
            addCriterion("resume_telno <>", value, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoGreaterThan(Long value) {
            addCriterion("resume_telno >", value, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoGreaterThanOrEqualTo(Long value) {
            addCriterion("resume_telno >=", value, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoLessThan(Long value) {
            addCriterion("resume_telno <", value, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoLessThanOrEqualTo(Long value) {
            addCriterion("resume_telno <=", value, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoIn(List<Long> values) {
            addCriterion("resume_telno in", values, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoNotIn(List<Long> values) {
            addCriterion("resume_telno not in", values, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoBetween(Long value1, Long value2) {
            addCriterion("resume_telno between", value1, value2, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeTelnoNotBetween(Long value1, Long value2) {
            addCriterion("resume_telno not between", value1, value2, "resumeTelno");
            return (Criteria) this;
        }

        public Criteria andResumeEmailIsNull() {
            addCriterion("resume_email is null");
            return (Criteria) this;
        }

        public Criteria andResumeEmailIsNotNull() {
            addCriterion("resume_email is not null");
            return (Criteria) this;
        }

        public Criteria andResumeEmailEqualTo(String value) {
            addCriterion("resume_email =", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailNotEqualTo(String value) {
            addCriterion("resume_email <>", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailGreaterThan(String value) {
            addCriterion("resume_email >", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailGreaterThanOrEqualTo(String value) {
            addCriterion("resume_email >=", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailLessThan(String value) {
            addCriterion("resume_email <", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailLessThanOrEqualTo(String value) {
            addCriterion("resume_email <=", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailLike(String value) {
            addCriterion("resume_email like", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailNotLike(String value) {
            addCriterion("resume_email not like", value, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailIn(List<String> values) {
            addCriterion("resume_email in", values, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailNotIn(List<String> values) {
            addCriterion("resume_email not in", values, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailBetween(String value1, String value2) {
            addCriterion("resume_email between", value1, value2, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeEmailNotBetween(String value1, String value2) {
            addCriterion("resume_email not between", value1, value2, "resumeEmail");
            return (Criteria) this;
        }

        public Criteria andResumeGenderIsNull() {
            addCriterion("resume_gender is null");
            return (Criteria) this;
        }

        public Criteria andResumeGenderIsNotNull() {
            addCriterion("resume_gender is not null");
            return (Criteria) this;
        }

        public Criteria andResumeGenderEqualTo(String value) {
            addCriterion("resume_gender =", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderNotEqualTo(String value) {
            addCriterion("resume_gender <>", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderGreaterThan(String value) {
            addCriterion("resume_gender >", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderGreaterThanOrEqualTo(String value) {
            addCriterion("resume_gender >=", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderLessThan(String value) {
            addCriterion("resume_gender <", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderLessThanOrEqualTo(String value) {
            addCriterion("resume_gender <=", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderLike(String value) {
            addCriterion("resume_gender like", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderNotLike(String value) {
            addCriterion("resume_gender not like", value, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderIn(List<String> values) {
            addCriterion("resume_gender in", values, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderNotIn(List<String> values) {
            addCriterion("resume_gender not in", values, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderBetween(String value1, String value2) {
            addCriterion("resume_gender between", value1, value2, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeGenderNotBetween(String value1, String value2) {
            addCriterion("resume_gender not between", value1, value2, "resumeGender");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingIsNull() {
            addCriterion("resume_leaving__working is null");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingIsNotNull() {
            addCriterion("resume_leaving__working is not null");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingEqualTo(String value) {
            addCriterion("resume_leaving__working =", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingNotEqualTo(String value) {
            addCriterion("resume_leaving__working <>", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingGreaterThan(String value) {
            addCriterion("resume_leaving__working >", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingGreaterThanOrEqualTo(String value) {
            addCriterion("resume_leaving__working >=", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingLessThan(String value) {
            addCriterion("resume_leaving__working <", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingLessThanOrEqualTo(String value) {
            addCriterion("resume_leaving__working <=", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingLike(String value) {
            addCriterion("resume_leaving__working like", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingNotLike(String value) {
            addCriterion("resume_leaving__working not like", value, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingIn(List<String> values) {
            addCriterion("resume_leaving__working in", values, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingNotIn(List<String> values) {
            addCriterion("resume_leaving__working not in", values, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingBetween(String value1, String value2) {
            addCriterion("resume_leaving__working between", value1, value2, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLeavingWorkingNotBetween(String value1, String value2) {
            addCriterion("resume_leaving__working not between", value1, value2, "resumeLeavingWorking");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityIsNull() {
            addCriterion("resume_live_city is null");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityIsNotNull() {
            addCriterion("resume_live_city is not null");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityEqualTo(String value) {
            addCriterion("resume_live_city =", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityNotEqualTo(String value) {
            addCriterion("resume_live_city <>", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityGreaterThan(String value) {
            addCriterion("resume_live_city >", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityGreaterThanOrEqualTo(String value) {
            addCriterion("resume_live_city >=", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityLessThan(String value) {
            addCriterion("resume_live_city <", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityLessThanOrEqualTo(String value) {
            addCriterion("resume_live_city <=", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityLike(String value) {
            addCriterion("resume_live_city like", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityNotLike(String value) {
            addCriterion("resume_live_city not like", value, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityIn(List<String> values) {
            addCriterion("resume_live_city in", values, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityNotIn(List<String> values) {
            addCriterion("resume_live_city not in", values, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityBetween(String value1, String value2) {
            addCriterion("resume_live_city between", value1, value2, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumeLiveCityNotBetween(String value1, String value2) {
            addCriterion("resume_live_city not between", value1, value2, "resumeLiveCity");
            return (Criteria) this;
        }

        public Criteria andResumePersonidIsNull() {
            addCriterion("resume_personid is null");
            return (Criteria) this;
        }

        public Criteria andResumePersonidIsNotNull() {
            addCriterion("resume_personid is not null");
            return (Criteria) this;
        }

        public Criteria andResumePersonidEqualTo(String value) {
            addCriterion("resume_personid =", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidNotEqualTo(String value) {
            addCriterion("resume_personid <>", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidGreaterThan(String value) {
            addCriterion("resume_personid >", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidGreaterThanOrEqualTo(String value) {
            addCriterion("resume_personid >=", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidLessThan(String value) {
            addCriterion("resume_personid <", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidLessThanOrEqualTo(String value) {
            addCriterion("resume_personid <=", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidLike(String value) {
            addCriterion("resume_personid like", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidNotLike(String value) {
            addCriterion("resume_personid not like", value, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidIn(List<String> values) {
            addCriterion("resume_personid in", values, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidNotIn(List<String> values) {
            addCriterion("resume_personid not in", values, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidBetween(String value1, String value2) {
            addCriterion("resume_personid between", value1, value2, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumePersonidNotBetween(String value1, String value2) {
            addCriterion("resume_personid not between", value1, value2, "resumePersonid");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeIsNull() {
            addCriterion("resume_income is null");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeIsNotNull() {
            addCriterion("resume_income is not null");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeEqualTo(Integer value) {
            addCriterion("resume_income =", value, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeNotEqualTo(Integer value) {
            addCriterion("resume_income <>", value, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeGreaterThan(Integer value) {
            addCriterion("resume_income >", value, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("resume_income >=", value, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeLessThan(Integer value) {
            addCriterion("resume_income <", value, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeLessThanOrEqualTo(Integer value) {
            addCriterion("resume_income <=", value, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeIn(List<Integer> values) {
            addCriterion("resume_income in", values, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeNotIn(List<Integer> values) {
            addCriterion("resume_income not in", values, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeBetween(Integer value1, Integer value2) {
            addCriterion("resume_income between", value1, value2, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeIncomeNotBetween(Integer value1, Integer value2) {
            addCriterion("resume_income not between", value1, value2, "resumeIncome");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeIsNull() {
            addCriterion("resume_full_part_time is null");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeIsNotNull() {
            addCriterion("resume_full_part_time is not null");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeEqualTo(String value) {
            addCriterion("resume_full_part_time =", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeNotEqualTo(String value) {
            addCriterion("resume_full_part_time <>", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeGreaterThan(String value) {
            addCriterion("resume_full_part_time >", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeGreaterThanOrEqualTo(String value) {
            addCriterion("resume_full_part_time >=", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeLessThan(String value) {
            addCriterion("resume_full_part_time <", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeLessThanOrEqualTo(String value) {
            addCriterion("resume_full_part_time <=", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeLike(String value) {
            addCriterion("resume_full_part_time like", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeNotLike(String value) {
            addCriterion("resume_full_part_time not like", value, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeIn(List<String> values) {
            addCriterion("resume_full_part_time in", values, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeNotIn(List<String> values) {
            addCriterion("resume_full_part_time not in", values, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeBetween(String value1, String value2) {
            addCriterion("resume_full_part_time between", value1, value2, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andResumeFullPartTimeNotBetween(String value1, String value2) {
            addCriterion("resume_full_part_time not between", value1, value2, "resumeFullPartTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resume
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 26 09:56:38 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resume
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}